"""
FlashWords vocabulary generator.

Produces public/flashcards.json from a CURATED, grammatically-correct dataset.
Unlike the old generator, there are NO machine-built "phrase" cards with broken
grammar. Every entry below is hand-written:
  - nouns carry their correct gender (en / ei / et)
  - every card has a real, idiomatic Norwegian example sentence + English gloss

The dataset is split into batches so it can grow toward ~1000 cards over time
while keeping quality high. Run:  python scripts/generate_vocab.py
It writes ../public/flashcards.json (ids are stable, derived from the word).
"""

import json
import os
import uuid

NAMESPACE = uuid.UUID("6b3c2f1a-0d4e-4a8b-9c11-7e2a5d6f8b00")


def stable_id(norwegian: str, pos: str) -> str:
    """Deterministic id so re-running doesn't churn ids (good for git diffs)."""
    return str(uuid.uuid5(NAMESPACE, f"{pos}:{norwegian}"))


def card(no, en, pos, ex_no, ex_en, gender=None, level="beginner"):
    c = {
        "id": stable_id(no, pos),
        "norwegianWord": no,
        "englishMeaning": en,
        "partOfSpeech": pos,
        "exampleNorwegian": ex_no,
        "exampleEnglish": ex_en,
        "difficultyLevel": level,
    }
    if gender:
        c["gender"] = gender
    return c


# ---------------------------------------------------------------------------
# NOUNS  — (norwegian, english, gender, example_no, example_en)
# ---------------------------------------------------------------------------
NOUNS = [
    ("hus", "house", "et", "Huset er stort og hvitt.", "The house is big and white."),
    ("bil", "car", "en", "Bilen min er rød.", "My car is red."),
    ("katt", "cat", "en", "Katten sover i sofaen.", "The cat is sleeping on the sofa."),
    ("hund", "dog", "en", "Hunden løper i hagen.", "The dog runs in the garden."),
    ("eple", "apple", "et", "Jeg spiser et eple hver dag.", "I eat an apple every day."),
    ("bok", "book", "ei", "Boka ligger på bordet.", "The book is on the table."),
    ("dør", "door", "ei", "Lukk døra, er du snill.", "Close the door, please."),
    ("vindu", "window", "et", "Vinduet er åpent.", "The window is open."),
    ("stol", "chair", "en", "Han sitter på en stol.", "He is sitting on a chair."),
    ("bord", "table", "et", "Maten står på bordet.", "The food is on the table."),
    ("brød", "bread", "et", "Vi kjøper ferskt brød.", "We buy fresh bread."),
    ("vann", "water", "et", "Kan jeg få et glass vann?", "Can I have a glass of water?"),
    ("kaffe", "coffee", "en", "Jeg drikker kaffe om morgenen.", "I drink coffee in the morning."),
    ("te", "tea", "en", "Hun liker te med melk.", "She likes tea with milk."),
    ("ost", "cheese", "en", "Osten smaker godt.", "The cheese tastes good."),
    ("melk", "milk", "ei", "Barna drikker melk.", "The children drink milk."),
    ("egg", "egg", "et", "Jeg koker et egg.", "I am boiling an egg."),
    ("fisk", "fish", "en", "Vi spiser fisk på fredag.", "We eat fish on Friday."),
    ("kjøtt", "meat", "et", "Han spiser ikke kjøtt.", "He does not eat meat."),
    ("potet", "potato", "en", "Poteten er kokt.", "The potato is boiled."),
    ("skole", "school", "en", "Skolen begynner klokka åtte.", "School starts at eight o'clock."),
    ("lærer", "teacher", "en", "Læreren er veldig snill.", "The teacher is very kind."),
    ("elev", "pupil", "en", "Eleven gjør leksene sine.", "The pupil does their homework."),
    ("klasse", "class", "en", "Klassen min har tjue elever.", "My class has twenty pupils."),
    ("blyant", "pencil", "en", "Kan jeg låne en blyant?", "Can I borrow a pencil?"),
    ("papir", "paper", "et", "Skriv navnet ditt på papiret.", "Write your name on the paper."),
    ("telefon", "phone", "en", "Telefonen min er tom for strøm.", "My phone is out of battery."),
    ("vei", "road", "en", "Veien er glatt om vinteren.", "The road is slippery in winter."),
    ("gate", "street", "ei", "Vi bor i en rolig gate.", "We live on a quiet street."),
    ("by", "city", "en", "Oslo er en fin by.", "Oslo is a nice city."),
    ("land", "country", "et", "Norge er et vakkert land.", "Norway is a beautiful country."),
    ("skog", "forest", "en", "Vi går tur i skogen.", "We go for a walk in the forest."),
    ("fjell", "mountain", "et", "Fjellet er dekket av snø.", "The mountain is covered in snow."),
    ("elv", "river", "ei", "Elva renner gjennom byen.", "The river runs through the city."),
    ("hav", "ocean", "et", "Havet er kaldt i dag.", "The ocean is cold today."),
    ("himmel", "sky", "en", "Himmelen er blå.", "The sky is blue."),
    ("sol", "sun", "ei", "Sola skinner i dag.", "The sun is shining today."),
    ("måne", "moon", "en", "Månen lyser om natta.", "The moon shines at night."),
    ("stjerne", "star", "ei", "Vi ser på stjernene.", "We are looking at the stars."),
    ("dag", "day", "en", "Ha en fin dag!", "Have a nice day!"),
    ("natt", "night", "ei", "God natt!", "Good night!"),
    ("morgen", "morning", "en", "Vi spiser frokost om morgenen.", "We eat breakfast in the morning."),
    ("kveld", "evening", "en", "Jeg leser om kvelden.", "I read in the evening."),
    ("uke", "week", "ei", "Jeg jobber fem dager i uka.", "I work five days a week."),
    ("måned", "month", "en", "Januar er en kald måned.", "January is a cold month."),
    ("år", "year", "et", "Godt nytt år!", "Happy new year!"),
    ("time", "hour", "en", "Filmen varer to timer.", "The film lasts two hours."),
    ("jente", "girl", "ei", "Jenta leker ute.", "The girl is playing outside."),
    ("gutt", "boy", "en", "Gutten spiller fotball.", "The boy is playing football."),
    ("kvinne", "woman", "ei", "Kvinnen jobber på sykehuset.", "The woman works at the hospital."),
    ("mann", "man", "en", "Mannen leser avisa.", "The man is reading the newspaper."),
    ("venn", "friend", "en", "Han er en god venn.", "He is a good friend."),
    ("familie", "family", "en", "Familien min er stor.", "My family is big."),
    ("mor", "mother", "ei", "Mora mi heter Anne.", "My mother's name is Anne."),
    ("far", "father", "en", "Faren min jobber mye.", "My father works a lot."),
    ("søster", "sister", "ei", "Søstera mi er eldre enn meg.", "My sister is older than me."),
    ("bror", "brother", "en", "Broren min bor i Bergen.", "My brother lives in Bergen."),
    ("barn", "child", "et", "Barnet sover.", "The child is sleeping."),
    ("hode", "head", "et", "Jeg har vondt i hodet.", "I have a headache."),
    ("hånd", "hand", "ei", "Vask hendene dine.", "Wash your hands."),
    ("fot", "foot", "en", "Foten min gjør vondt.", "My foot hurts."),
    ("øye", "eye", "et", "Hun har blå øyne.", "She has blue eyes."),
    ("hjerte", "heart", "et", "Hjertet slår fort.", "The heart is beating fast."),
    ("tog", "train", "et", "Toget går klokka ni.", "The train leaves at nine o'clock."),
    ("buss", "bus", "en", "Bussen er forsinket.", "The bus is delayed."),
    ("fly", "airplane", "et", "Flyet lander snart.", "The plane is landing soon."),
    ("båt", "boat", "en", "Vi seiler med båten.", "We sail with the boat."),
    ("sykkel", "bicycle", "en", "Jeg sykler til jobben på sykkelen.", "I bike to work on my bicycle."),
    ("billett", "ticket", "en", "Jeg kjøpte en billett til konserten.", "I bought a ticket to the concert."),
    ("mat", "food", "en", "Maten er klar.", "The food is ready."),
    ("frokost", "breakfast", "en", "Frokost er det viktigste måltidet.", "Breakfast is the most important meal."),
    ("lunsj", "lunch", "en", "Vi spiser lunsj klokka tolv.", "We eat lunch at twelve o'clock."),
    ("middag", "dinner", "en", "Middagen smaker fantastisk.", "The dinner tastes amazing."),
    ("kniv", "knife", "en", "Kniven er skarp.", "The knife is sharp."),
    ("gaffel", "fork", "en", "Bruk gaffel og kniv.", "Use a fork and knife."),
    ("skje", "spoon", "ei", "Han spiser suppe med en skje.", "He eats soup with a spoon."),
    ("kopp", "cup", "en", "En kopp kaffe, takk.", "A cup of coffee, please."),
    ("glass", "glass", "et", "Glasset er fullt.", "The glass is full."),
    ("farge", "color", "en", "Hva er favorittfargen din?", "What is your favorite color?"),
    ("klær", "clothes", "en", "Klærne er rene.", "The clothes are clean."),
    ("jakke", "jacket", "ei", "Ta på deg jakka, det er kaldt.", "Put on your jacket, it's cold."),
    ("bukse", "trousers", "ei", "Buksa er for lang.", "The trousers are too long."),
    ("genser", "sweater", "en", "Genseren er varm.", "The sweater is warm."),
    ("sko", "shoe", "en", "Skoene mine er våte.", "My shoes are wet."),
    ("hjem", "home", "et", "Det er godt å komme hjem.", "It's good to come home."),
    ("rom", "room", "et", "Rommet er rent.", "The room is clean."),
    ("kjøkken", "kitchen", "et", "Hun lager mat på kjøkkenet.", "She cooks in the kitchen."),
    ("bad", "bathroom", "et", "Badet er på venstre side.", "The bathroom is on the left."),
    ("seng", "bed", "ei", "Jeg går til senga.", "I'm going to bed."),
    ("penger", "money", "en", "Jeg har ikke nok penger.", "I don't have enough money."),
    ("jobb", "job", "en", "Hun har en ny jobb.", "She has a new job."),
    ("arbeid", "work", "et", "Arbeidet er ferdig.", "The work is finished."),
    ("butikk", "shop", "en", "Butikken stenger klokka seks.", "The shop closes at six o'clock."),
    ("sykehus", "hospital", "et", "Hun jobber på sykehuset.", "She works at the hospital."),
    ("lege", "doctor", "en", "Jeg må til legen.", "I have to go to the doctor."),
    ("vær", "weather", "et", "Været er fint i dag.", "The weather is nice today."),
    ("regn", "rain", "et", "Regnet stoppet aldri.", "The rain never stopped."),
    ("snø", "snow", "en", "Snøen dekker bakken.", "The snow covers the ground."),
    ("vind", "wind", "en", "Vinden er sterk i dag.", "The wind is strong today."),
    ("navn", "name", "et", "Hva er navnet ditt?", "What is your name?"),
    ("språk", "language", "et", "Norsk er et fint språk.", "Norwegian is a nice language."),
    ("ord", "word", "et", "Jeg lærer ti nye ord hver dag.", "I learn ten new words every day."),
    ("spørsmål", "question", "et", "Jeg har et spørsmål.", "I have a question."),
    ("svar", "answer", "et", "Svaret er riktig.", "The answer is correct."),
]

# ---------------------------------------------------------------------------
# VERBS  — stored without "å"; (root_no, en, example_no, example_en)
# norwegianWord becomes "å <root>", english becomes "to <en>"
# ---------------------------------------------------------------------------
VERBS = [
    ("være", "be", "Jeg vil være lærer.", "I want to be a teacher."),
    ("ha", "have", "Vi har en hund.", "We have a dog."),
    ("gjøre", "do", "Hva gjør du nå?", "What are you doing now?"),
    ("si", "say", "Hva sa du?", "What did you say?"),
    ("gå", "walk", "Vi går til skolen.", "We walk to school."),
    ("få", "get", "Kan jeg få litt vann?", "Can I get some water?"),
    ("vite", "know", "Jeg vet ikke svaret.", "I don't know the answer."),
    ("se", "see", "Jeg ser deg!", "I see you!"),
    ("komme", "come", "Når kommer du?", "When are you coming?"),
    ("tenke", "think", "Jeg tenker på deg.", "I'm thinking about you."),
    ("spise", "eat", "Vi spiser middag klokka seks.", "We eat dinner at six o'clock."),
    ("drikke", "drink", "Han drikker vann.", "He drinks water."),
    ("sove", "sleep", "Barnet sover godt.", "The child sleeps well."),
    ("bo", "live", "Jeg bor i Oslo.", "I live in Oslo."),
    ("hete", "be called", "Jeg heter Maria.", "My name is Maria."),
    ("elske", "love", "Jeg elsker deg.", "I love you."),
    ("like", "like", "Jeg liker kaffe.", "I like coffee."),
    ("lese", "read", "Hun leser ei bok.", "She is reading a book."),
    ("skrive", "write", "Jeg skriver et brev.", "I am writing a letter."),
    ("lære", "learn", "Vi lærer norsk.", "We are learning Norwegian."),
    ("snakke", "speak", "Snakker du engelsk?", "Do you speak English?"),
    ("kjøpe", "buy", "Jeg vil kjøpe brød.", "I want to buy bread."),
    ("selge", "sell", "De selger huset.", "They are selling the house."),
    ("betale", "pay", "Jeg må betale regningen.", "I have to pay the bill."),
    ("jobbe", "work", "Hun jobber på et kontor.", "She works in an office."),
    ("spille", "play", "Guttene spiller fotball.", "The boys are playing football."),
    ("synge", "sing", "Hun synger vakkert.", "She sings beautifully."),
    ("danse", "dance", "Vi danser hele natta.", "We dance all night."),
    ("høre", "hear", "Hører du musikken?", "Do you hear the music?"),
    ("føle", "feel", "Jeg føler meg trøtt.", "I feel tired."),
    ("stå", "stand", "Han står ved døra.", "He is standing by the door."),
    ("sitte", "sit", "Vi sitter i sofaen.", "We are sitting on the sofa."),
    ("løpe", "run", "Hunden løper fort.", "The dog runs fast."),
    ("svømme", "swim", "Jeg liker å svømme om sommeren.", "I like to swim in the summer."),
    ("kjøre", "drive", "Han kjører til jobben.", "He drives to work."),
    ("reise", "travel", "Vi reiser til Spania.", "We are traveling to Spain."),
    ("lage", "make", "Jeg lager middag.", "I am making dinner."),
    ("åpne", "open", "Kan du åpne vinduet?", "Can you open the window?"),
    ("lukke", "close", "Lukk døra, takk.", "Close the door, please."),
    ("begynne", "begin", "Filmen begynner nå.", "The film is beginning now."),
    ("slutte", "stop", "Jeg vil slutte å røyke.", "I want to stop smoking."),
    ("hjelpe", "help", "Kan du hjelpe meg?", "Can you help me?"),
    ("ville", "want", "Jeg vil ha en kaffe.", "I want a coffee."),
    ("kunne", "can", "Jeg kan snakke litt norsk.", "I can speak a little Norwegian."),
    ("måtte", "must", "Jeg må gå nå.", "I must go now."),
    ("bruke", "use", "Jeg bruker telefonen ofte.", "I use the phone often."),
    ("vente", "wait", "Vent litt!", "Wait a moment!"),
    ("tro", "believe", "Jeg tror det blir fint vær.", "I believe the weather will be nice."),
    ("håpe", "hope", "Jeg håper du har det bra.", "I hope you are well."),
    ("forstå", "understand", "Jeg forstår ikke.", "I don't understand."),
    ("huske", "remember", "Husker du navnet hans?", "Do you remember his name?"),
    ("glemme", "forget", "Ikke glem nøklene!", "Don't forget the keys!"),
    ("spørre", "ask", "Jeg vil spørre om noe.", "I want to ask about something."),
    ("svare", "answer", "Hun svarte ikke på telefonen.", "She didn't answer the phone."),
    ("le", "laugh", "Vi ler mye sammen.", "We laugh a lot together."),
    ("gråte", "cry", "Babyen gråter.", "The baby is crying."),
    ("smile", "smile", "Hun smiler alltid.", "She always smiles."),
    ("leve", "live", "Vi lever et godt liv.", "We live a good life."),
    ("dø", "die", "Blomsten døde i vinter.", "The flower died in winter."),
    ("bygge", "build", "De bygger et nytt hus.", "They are building a new house."),
    ("møte", "meet", "Vi møtes i morgen.", "We are meeting tomorrow."),
    ("vise", "show", "Kan du vise meg veien?", "Can you show me the way?"),
    ("finne", "find", "Jeg kan ikke finne nøklene.", "I can't find the keys."),
    ("gi", "give", "Gi meg boka, takk.", "Give me the book, please."),
    ("ta", "take", "Ta en stol.", "Take a chair."),
    ("sende", "send", "Jeg sender deg en melding.", "I'll send you a message."),
    ("ringe", "call", "Jeg ringer deg senere.", "I'll call you later."),
    ("trenge", "need", "Jeg trenger hjelp.", "I need help."),
]

# ---------------------------------------------------------------------------
# ADJECTIVES  — (no, en, example_no, example_en)
# ---------------------------------------------------------------------------
ADJECTIVES = [
    ("stor", "big", "Huset er stort.", "The house is big."),
    ("liten", "small", "Katten er liten.", "The cat is small."),
    ("god", "good", "Maten er god.", "The food is good."),
    ("dårlig", "bad", "Været er dårlig i dag.", "The weather is bad today."),
    ("ny", "new", "Jeg har en ny bil.", "I have a new car."),
    ("gammel", "old", "Huset er veldig gammelt.", "The house is very old."),
    ("varm", "warm", "Kaffen er varm.", "The coffee is warm."),
    ("kald", "cold", "Vannet er kaldt.", "The water is cold."),
    ("dyr", "expensive", "Bilen er for dyr.", "The car is too expensive."),
    ("billig", "cheap", "Maten her er billig.", "The food here is cheap."),
    ("glad", "happy", "Jeg er glad i dag.", "I am happy today."),
    ("trist", "sad", "Hun ser trist ut.", "She looks sad."),
    ("sulten", "hungry", "Jeg er sulten.", "I am hungry."),
    ("tørst", "thirsty", "Er du tørst?", "Are you thirsty?"),
    ("trøtt", "tired", "Barna er trøtte.", "The children are tired."),
    ("rød", "red", "Eplet er rødt.", "The apple is red."),
    ("blå", "blue", "Himmelen er blå.", "The sky is blue."),
    ("grønn", "green", "Gresset er grønt.", "The grass is green."),
    ("gul", "yellow", "Sola er gul.", "The sun is yellow."),
    ("svart", "black", "Katten er svart.", "The cat is black."),
    ("hvit", "white", "Snøen er hvit.", "The snow is white."),
    ("fin", "nice", "Det er en fin dag.", "It is a nice day."),
    ("pen", "pretty", "Hun har en pen kjole.", "She has a pretty dress."),
    ("vakker", "beautiful", "Naturen er vakker.", "The nature is beautiful."),
    ("sterk", "strong", "Han er veldig sterk.", "He is very strong."),
    ("svak", "weak", "Teen er for svak.", "The tea is too weak."),
    ("lang", "long", "Det er en lang vei.", "It is a long road."),
    ("kort", "short", "Filmen var kort.", "The film was short."),
    ("høy", "tall", "Han er veldig høy.", "He is very tall."),
    ("rask", "fast", "Toget er raskt.", "The train is fast."),
    ("langsom", "slow", "Bussen er langsom.", "The bus is slow."),
    ("viktig", "important", "Dette er veldig viktig.", "This is very important."),
    ("riktig", "correct", "Svaret er riktig.", "The answer is correct."),
    ("vanskelig", "difficult", "Norsk er ikke vanskelig.", "Norwegian is not difficult."),
    ("lett", "easy", "Oppgaven var lett.", "The task was easy."),
    ("tung", "heavy", "Kofferten er tung.", "The suitcase is heavy."),
    ("full", "full", "Glasset er fullt.", "The glass is full."),
    ("tom", "empty", "Flaska er tom.", "The bottle is empty."),
    ("ren", "clean", "Klærne er rene.", "The clothes are clean."),
    ("skitten", "dirty", "Skoene er skitne.", "The shoes are dirty."),
    ("syk", "sick", "Jeg er syk i dag.", "I am sick today."),
    ("frisk", "healthy", "Hun er frisk igjen.", "She is healthy again."),
    ("snill", "kind", "Læreren er snill.", "The teacher is kind."),
    ("morsom", "funny", "Filmen var morsom.", "The film was funny."),
    ("kjedelig", "boring", "Boka var kjedelig.", "The book was boring."),
    ("redd", "scared", "Hunden er redd for torden.", "The dog is scared of thunder."),
    ("rolig", "calm", "Sjøen er rolig i dag.", "The sea is calm today."),
    ("travel", "busy", "Jeg har en travel dag.", "I have a busy day."),
    ("vakker", "lovely", "For en vakker sang!", "What a lovely song!"),
    ("deilig", "delicious", "Maten var deilig.", "The food was delicious."),
]

# ---------------------------------------------------------------------------
# OTHER  — adverbs, pronouns, prepositions, conjunctions, question words,
#          numbers. (no, en, pos, example_no, example_en)
# ---------------------------------------------------------------------------
OTHER = [
    ("jeg", "I", "pronoun", "Jeg heter Ola.", "My name is Ola."),
    ("du", "you", "pronoun", "Hvor bor du?", "Where do you live?"),
    ("han", "he", "pronoun", "Han er bror min.", "He is my brother."),
    ("hun", "she", "pronoun", "Hun jobber på sykehuset.", "She works at the hospital."),
    ("vi", "we", "pronoun", "Vi bor i Norge.", "We live in Norway."),
    ("de", "they", "pronoun", "De kommer i kveld.", "They are coming tonight."),
    ("ja", "yes", "adverb", "Ja, det stemmer.", "Yes, that's right."),
    ("nei", "no", "adverb", "Nei, takk.", "No, thank you."),
    ("ikke", "not", "adverb", "Jeg forstår ikke.", "I don't understand."),
    ("og", "and", "conjunction", "Brød og smør.", "Bread and butter."),
    ("eller", "or", "conjunction", "Te eller kaffe?", "Tea or coffee?"),
    ("men", "but", "conjunction", "Jeg er trøtt, men glad.", "I am tired, but happy."),
    ("fordi", "because", "conjunction", "Jeg blir hjemme fordi jeg er syk.", "I'm staying home because I'm sick."),
    ("her", "here", "adverb", "Jeg er her.", "I am here."),
    ("der", "there", "adverb", "Boka ligger der.", "The book is over there."),
    ("nå", "now", "adverb", "Vi må gå nå.", "We have to go now."),
    ("alltid", "always", "adverb", "Hun er alltid blid.", "She is always cheerful."),
    ("aldri", "never", "adverb", "Jeg glemmer det aldri.", "I will never forget it."),
    ("ofte", "often", "adverb", "Vi går ofte på tur.", "We often go for walks."),
    ("kanskje", "maybe", "adverb", "Kanskje det regner i morgen.", "Maybe it will rain tomorrow."),
    ("veldig", "very", "adverb", "Det er veldig kaldt ute.", "It is very cold outside."),
    ("litt", "a little", "adverb", "Jeg snakker litt norsk.", "I speak a little Norwegian."),
    ("mye", "much", "adverb", "Takk så mye!", "Thank you so much!"),
    ("i", "in", "preposition", "Vi bor i Norge.", "We live in Norway."),
    ("på", "on", "preposition", "Boka ligger på bordet.", "The book is on the table."),
    ("til", "to", "preposition", "Jeg går til skolen.", "I am going to school."),
    ("fra", "from", "preposition", "Jeg kommer fra India.", "I come from India."),
    ("med", "with", "preposition", "Jeg drikker te med melk.", "I drink tea with milk."),
    ("uten", "without", "preposition", "Kaffe uten sukker, takk.", "Coffee without sugar, please."),
    ("under", "under", "preposition", "Katten ligger under bordet.", "The cat is lying under the table."),
    ("over", "over", "preposition", "Flyet flyr over byen.", "The plane flies over the city."),
    ("hva", "what", "question", "Hva heter du?", "What is your name?"),
    ("hvem", "who", "question", "Hvem er det?", "Who is it?"),
    ("hvor", "where", "question", "Hvor bor du?", "Where do you live?"),
    ("når", "when", "question", "Når kommer toget?", "When does the train come?"),
    ("hvorfor", "why", "question", "Hvorfor gråter du?", "Why are you crying?"),
    ("hvordan", "how", "question", "Hvordan går det?", "How are you?"),
    ("en", "one", "number", "Jeg vil ha én kopp kaffe.", "I want one cup of coffee."),
    ("to", "two", "number", "Vi har to barn.", "We have two children."),
    ("tre", "three", "number", "Klokka er tre.", "It is three o'clock."),
    ("fire", "four", "number", "Bordet har fire bein.", "The table has four legs."),
    ("fem", "five", "number", "Jeg jobber fem dager i uka.", "I work five days a week."),
    ("seks", "six", "number", "Hun står opp klokka seks.", "She gets up at six o'clock."),
    ("sju", "seven", "number", "Det er sju dager i en uke.", "There are seven days in a week."),
    ("åtte", "eight", "number", "Skolen begynner klokka åtte.", "School begins at eight o'clock."),
    ("ni", "nine", "number", "Butikken åpner klokka ni.", "The shop opens at nine o'clock."),
    ("ti", "ten", "number", "Jeg har ti fingre.", "I have ten fingers."),
]

# ---------------------------------------------------------------------------
# PHRASES  — everyday expressions. (no, en) ; pos="phrase", intermediate
# ---------------------------------------------------------------------------
PHRASES = [
    ("Hei!", "Hi!"),
    ("God morgen!", "Good morning!"),
    ("God dag!", "Good day!"),
    ("God kveld!", "Good evening!"),
    ("Ha det bra!", "Goodbye!"),
    ("Vi ses!", "See you!"),
    ("Takk!", "Thank you!"),
    ("Tusen takk!", "Thanks a lot!"),
    ("Vær så snill.", "Please."),
    ("Vær så god.", "Here you go. / You're welcome."),
    ("Unnskyld meg.", "Excuse me."),
    ("Beklager.", "I'm sorry."),
    ("Ingen problem.", "No problem."),
    ("Hvordan går det?", "How are you?"),
    ("Det går bra, takk.", "I'm fine, thanks."),
    ("Hva heter du?", "What's your name?"),
    ("Jeg heter ...", "My name is ..."),
    ("Hyggelig å møte deg.", "Nice to meet you."),
    ("Snakker du engelsk?", "Do you speak English?"),
    ("Jeg forstår ikke.", "I don't understand."),
    ("Kan du gjenta det?", "Can you repeat that?"),
    ("Kan du snakke saktere?", "Can you speak more slowly?"),
    ("Hva betyr dette?", "What does this mean?"),
    ("Hvor er toalettet?", "Where is the toilet?"),
    ("Hvor mye koster det?", "How much does it cost?"),
    ("Regningen, takk.", "The bill, please."),
    ("Jeg vil gjerne ha en kaffe.", "I would like a coffee."),
    ("Kan jeg få menyen?", "Can I have the menu?"),
    ("Jeg er allergisk mot nøtter.", "I am allergic to nuts."),
    ("Bare hyggelig.", "You're welcome."),
    ("Jeg vet ikke.", "I don't know."),
    ("Jeg er enig.", "I agree."),
    ("Vent litt.", "Wait a moment."),
    ("Hjelp!", "Help!"),
    ("Jeg er fra India.", "I am from India."),
    ("Jeg lærer norsk.", "I am learning Norwegian."),
    ("Hvor er stasjonen?", "Where is the station?"),
    ("En billett til Oslo, takk.", "One ticket to Oslo, please."),
    ("Gratulerer med dagen!", "Happy birthday!"),
    ("Ha en fin dag!", "Have a nice day!"),
]




# ===========================================================================
# BATCH B — extended curated vocabulary (same format, same quality bar)
# ===========================================================================

NOUNS_B = [
    # --- animals ---
    ("fugl", "bird", "en", "Fuglen synger i treet.", "The bird is singing in the tree."),
    ("hest", "horse", "en", "Hesten løper på enga.", "The horse runs in the meadow."),
    ("ku", "cow", "ei", "Kua står på jordet.", "The cow is standing in the field."),
    ("gris", "pig", "en", "Grisen ligger i sølen.", "The pig is lying in the mud."),
    ("sau", "sheep", "en", "Sauen har tjukk ull.", "The sheep has thick wool."),
    ("geit", "goat", "ei", "Geita klatrer i fjellet.", "The goat climbs in the mountain."),
    ("mus", "mouse", "ei", "Musa gjemmer seg under gulvet.", "The mouse hides under the floor."),
    ("bjørn", "bear", "en", "Bjørnen sover om vinteren.", "The bear sleeps during the winter."),
    ("ulv", "wolf", "en", "Ulven hyler om natta.", "The wolf howls at night."),
    ("rev", "fox", "en", "Reven er lur.", "The fox is cunning."),
    ("elg", "moose", "en", "Vi så en elg i skogen.", "We saw a moose in the forest."),
    ("and", "duck", "ei", "Anda svømmer i dammen.", "The duck swims in the pond."),
    ("løve", "lion", "en", "Løven er kongen av savannen.", "The lion is the king of the savannah."),
    ("elefant", "elephant", "en", "Elefanten er et stort dyr.", "The elephant is a big animal."),
    ("slange", "snake", "en", "Slangen ligger i gresset.", "The snake lies in the grass."),
    ("frosk", "frog", "en", "Frosken hopper i vannet.", "The frog jumps into the water."),
    ("bie", "bee", "ei", "Bia lager honning.", "The bee makes honey."),
    ("maur", "ant", "en", "Mauren er liten, men sterk.", "The ant is small but strong."),
    ("sommerfugl", "butterfly", "en", "Sommerfuglen er vakker.", "The butterfly is beautiful."),
    ("kanin", "rabbit", "en", "Kaninen spiser gulrøtter.", "The rabbit eats carrots."),
    ("dyr", "animal", "et", "Hvilket dyr liker du best?", "Which animal do you like best?"),
    # --- body ---
    ("ansikt", "face", "et", "Hun har et vennlig ansikt.", "She has a friendly face."),
    ("nese", "nose", "ei", "Jeg har snørr i nesa.", "I have a runny nose."),
    ("øre", "ear", "et", "Jeg har vondt i øret.", "I have an earache."),
    ("munn", "mouth", "en", "Lukk munnen når du tygger.", "Close your mouth when you chew."),
    ("hals", "throat", "en", "Jeg har vondt i halsen.", "I have a sore throat."),
    ("arm", "arm", "en", "Han brakk armen.", "He broke his arm."),
    ("hår", "hair", "et", "Hun har langt, mørkt hår.", "She has long, dark hair."),
    ("rygg", "back", "en", "Ryggen min er stiv.", "My back is stiff."),
    ("mage", "stomach", "en", "Jeg har vondt i magen.", "I have a stomachache."),
    ("kne", "knee", "et", "Jeg falt og slo kneet.", "I fell and hit my knee."),
    ("bein", "leg/bone", "et", "Hunden gravde ned beinet.", "The dog buried the bone."),
    ("finger", "finger", "en", "Jeg skar meg i fingeren.", "I cut my finger."),
    ("tann", "tooth", "ei", "Tannen min gjør vondt.", "My tooth hurts."),
    ("skulder", "shoulder", "en", "Han la hånda på skulderen min.", "He put his hand on my shoulder."),
    ("hud", "skin", "en", "Sola er farlig for huden.", "The sun is dangerous for the skin."),
    ("blod", "blood", "et", "Blodet er rødt.", "Blood is red."),
    ("hjerne", "brain", "en", "Hjernen styrer kroppen.", "The brain controls the body."),
    ("kropp", "body", "en", "Trening er bra for kroppen.", "Exercise is good for the body."),
    # --- food & drink ---
    ("smør", "butter", "et", "Jeg smører smør på brødet.", "I spread butter on the bread."),
    ("sukker", "sugar", "et", "Vil du ha sukker i kaffen?", "Do you want sugar in your coffee?"),
    ("salt", "salt", "et", "Maten trenger litt salt.", "The food needs a little salt."),
    ("pepper", "pepper", "en", "Han bruker mye pepper.", "He uses a lot of pepper."),
    ("frukt", "fruit", "ei", "Frukt er sunt.", "Fruit is healthy."),
    ("grønnsak", "vegetable", "ei", "Spis grønnsakene dine.", "Eat your vegetables."),
    ("banan", "banana", "en", "Bananen er gul.", "The banana is yellow."),
    ("appelsin", "orange", "en", "Appelsinen er saftig.", "The orange is juicy."),
    ("jordbær", "strawberry", "et", "Jordbær smaker søtt.", "Strawberries taste sweet."),
    ("tomat", "tomato", "en", "Tomaten er rød og moden.", "The tomato is red and ripe."),
    ("løk", "onion", "en", "Løken får meg til å gråte.", "The onion makes me cry."),
    ("gulrot", "carrot", "ei", "Kaninen elsker gulrøtter.", "The rabbit loves carrots."),
    ("suppe", "soup", "ei", "Suppa er varm og god.", "The soup is warm and good."),
    ("salat", "salad", "en", "Jeg spiser salat til lunsj.", "I eat salad for lunch."),
    ("kake", "cake", "ei", "Vi spiser kake på bursdager.", "We eat cake on birthdays."),
    ("is", "ice cream", "en", "Barna vil ha is.", "The children want ice cream."),
    ("sjokolade", "chocolate", "en", "Sjokolade er min favoritt.", "Chocolate is my favorite."),
    ("juice", "juice", "en", "Jeg drikker juice til frokost.", "I drink juice for breakfast."),
    ("øl", "beer", "et", "Han bestilte et øl.", "He ordered a beer."),
    ("vin", "wine", "en", "De drikker rødvin til maten.", "They drink red wine with the food."),
    ("sjokoladekake", "chocolate cake", "ei", "Sjokoladekaka var nydelig.", "The chocolate cake was lovely."),
    # --- home & furniture ---
    ("sofa", "sofa", "en", "Vi sitter i sofaen og ser på TV.", "We sit on the sofa and watch TV."),
    ("lampe", "lamp", "ei", "Slå på lampa, det er mørkt.", "Turn on the lamp, it's dark."),
    ("teppe", "carpet/blanket", "et", "Teppet er mykt.", "The carpet is soft."),
    ("speil", "mirror", "et", "Hun ser seg i speilet.", "She looks at herself in the mirror."),
    ("hylle", "shelf", "ei", "Bøkene står i hylla.", "The books are on the shelf."),
    ("skap", "cupboard", "et", "Glassene står i skapet.", "The glasses are in the cupboard."),
    ("nøkkel", "key", "en", "Jeg mistet nøkkelen.", "I lost the key."),
    ("klokke", "clock/watch", "ei", "Klokka på veggen er stoppet.", "The clock on the wall has stopped."),
    ("bilde", "picture", "et", "Bildet henger på veggen.", "The picture hangs on the wall."),
    ("gardin", "curtain", "et", "Trekk for gardinene.", "Draw the curtains."),
    ("pute", "pillow", "ei", "Puta er myk.", "The pillow is soft."),
    ("dyne", "duvet", "ei", "Dyna holder meg varm.", "The duvet keeps me warm."),
    ("vegg", "wall", "en", "Veggen er malt blå.", "The wall is painted blue."),
    ("gulv", "floor", "et", "Gulvet er rent.", "The floor is clean."),
    ("tak", "roof/ceiling", "et", "Taket lekker når det regner.", "The roof leaks when it rains."),
    ("trapp", "stairs", "ei", "Vi går opp trappa.", "We walk up the stairs."),
    ("hage", "garden", "en", "Vi dyrker grønnsaker i hagen.", "We grow vegetables in the garden."),
    ("leilighet", "apartment", "ei", "De bor i en liten leilighet.", "They live in a small apartment."),
    # --- clothes ---
    ("skjorte", "shirt", "ei", "Skjorta er hvit.", "The shirt is white."),
    ("kjole", "dress", "en", "Hun har på seg en rød kjole.", "She is wearing a red dress."),
    ("hatt", "hat", "en", "Han tar av seg hatten.", "He takes off his hat."),
    ("lue", "beanie", "ei", "Ta på deg lua, det er kaldt.", "Put on your beanie, it's cold."),
    ("skjerf", "scarf", "et", "Skjerfet er av ull.", "The scarf is made of wool."),
    ("hanske", "glove", "en", "Jeg mistet en hanske.", "I lost a glove."),
    ("sokk", "sock", "en", "Sokken har et hull.", "The sock has a hole."),
    ("skjørt", "skirt", "et", "Skjørtet er for kort.", "The skirt is too short."),
    ("belte", "belt", "et", "Beltet er av lær.", "The belt is made of leather."),
    ("veske", "bag", "ei", "Veska er full av bøker.", "The bag is full of books."),
    ("klokke", "watch", "ei", "Klokka mi er av gull.", "My watch is made of gold."),
    ("ring", "ring", "en", "Hun har en ring på fingeren.", "She has a ring on her finger."),
    ("briller", "glasses", "en", "Jeg trenger brillene for å lese.", "I need glasses to read."),
    # --- nature & weather ---
    ("tre", "tree", "et", "Treet er hundre år gammelt.", "The tree is a hundred years old."),
    ("blomst", "flower", "en", "Blomsten lukter godt.", "The flower smells nice."),
    ("gress", "grass", "et", "Gresset er grønt om sommeren.", "The grass is green in summer."),
    ("blad", "leaf", "et", "Bladet faller fra treet.", "The leaf falls from the tree."),
    ("stein", "stone", "en", "Steinen er tung.", "The stone is heavy."),
    ("sand", "sand", "en", "Sanden er varm på stranda.", "The sand is warm on the beach."),
    ("strand", "beach", "ei", "Vi ligger på stranda.", "We lie on the beach."),
    ("innsjø", "lake", "en", "Innsjøen er rolig.", "The lake is calm."),
    ("øy", "island", "ei", "Vi reiser til ei lita øy.", "We travel to a small island."),
    ("sky", "cloud", "ei", "Det er mange skyer på himmelen.", "There are many clouds in the sky."),
    ("torden", "thunder", "en", "Hunden er redd for torden.", "The dog is scared of thunder."),
    ("lyn", "lightning", "et", "Lynet lyste opp himmelen.", "The lightning lit up the sky."),
    ("is", "ice", "en", "Isen på vannet er tykk.", "The ice on the water is thick."),
    ("vår", "spring", "en", "Blomstene kommer om våren.", "The flowers come in spring."),
    ("sommer", "summer", "en", "Vi bader om sommeren.", "We swim in the summer."),
    ("høst", "autumn", "en", "Bladene faller om høsten.", "The leaves fall in autumn."),
    ("vinter", "winter", "en", "Det snør om vinteren.", "It snows in winter."),
    ("natur", "nature", "en", "Norge har vakker natur.", "Norway has beautiful nature."),
    # --- places & buildings ---
    ("kirke", "church", "ei", "Kirka ligger midt i byen.", "The church is in the middle of town."),
    ("bibliotek", "library", "et", "Jeg låner bøker på biblioteket.", "I borrow books at the library."),
    ("museum", "museum", "et", "Museet er åpent på søndag.", "The museum is open on Sunday."),
    ("kino", "cinema", "en", "Vi går på kino i kveld.", "We are going to the cinema tonight."),
    ("kafé", "café", "en", "Vi møtes på en kafé.", "We meet at a café."),
    ("hotell", "hotel", "et", "Vi bor på et hotell i Oslo.", "We are staying at a hotel in Oslo."),
    ("flyplass", "airport", "en", "Vi må være på flyplassen tidlig.", "We have to be at the airport early."),
    ("stasjon", "station", "en", "Toget går fra stasjonen.", "The train leaves from the station."),
    ("bank", "bank", "en", "Banken stenger klokka tre.", "The bank closes at three o'clock."),
    ("apotek", "pharmacy", "et", "Jeg kjøper medisin på apoteket.", "I buy medicine at the pharmacy."),
    ("park", "park", "en", "Barna leker i parken.", "The children play in the park."),
    ("torg", "square", "et", "Det er marked på torget.", "There is a market on the square."),
    ("bro", "bridge", "ei", "Vi kjører over broa.", "We drive across the bridge."),
    ("kontor", "office", "et", "Hun jobber på et kontor.", "She works in an office."),
    ("fabrikk", "factory", "en", "Fabrikken lager biler.", "The factory makes cars."),
    ("gård", "farm", "en", "De bor på en gård.", "They live on a farm."),
    ("universitet", "university", "et", "Han studerer på universitetet.", "He studies at the university."),
    ("rådhus", "city hall", "et", "Rådhuset er en stor bygning.", "The city hall is a big building."),
    # --- transport ---
    ("trikk", "tram", "en", "Trikken stopper her.", "The tram stops here."),
    ("drosje", "taxi", "ei", "Vi tar en drosje hjem.", "We take a taxi home."),
    ("motorsykkel", "motorcycle", "en", "Han kjører motorsykkel.", "He rides a motorcycle."),
    ("lastebil", "truck", "en", "Lastebilen er full av varer.", "The truck is full of goods."),
    ("skip", "ship", "et", "Skipet seiler til Danmark.", "The ship sails to Denmark."),
    ("hjul", "wheel", "et", "Bilen har fire hjul.", "The car has four wheels."),
    ("motor", "engine", "en", "Motoren starter ikke.", "The engine won't start."),
    ("bensin", "petrol", "en", "Bilen er tom for bensin.", "The car is out of petrol."),
    ("vei", "way", "en", "Kan du vise meg veien?", "Can you show me the way?"),
    ("kart", "map", "et", "Vi ser på kartet.", "We look at the map."),
    # --- people & professions ---
    ("baby", "baby", "en", "Babyen sover godt.", "The baby is sleeping well."),
    ("nabo", "neighbor", "en", "Naboen vår er hyggelig.", "Our neighbor is friendly."),
    ("sjef", "boss", "en", "Sjefen min er streng.", "My boss is strict."),
    ("kunde", "customer", "en", "Kunden har alltid rett.", "The customer is always right."),
    ("politi", "police", "et", "Politiet kom raskt.", "The police came quickly."),
    ("brannmann", "firefighter", "en", "Brannmannen slukket brannen.", "The firefighter put out the fire."),
    ("sykepleier", "nurse", "en", "Sykepleieren hjelper pasientene.", "The nurse helps the patients."),
    ("kokk", "cook", "en", "Kokken lager nydelig mat.", "The cook makes delicious food."),
    ("sjåfør", "driver", "en", "Sjåføren kjører forsiktig.", "The driver drives carefully."),
    ("bonde", "farmer", "en", "Bonden står opp tidlig.", "The farmer gets up early."),
    ("kunstner", "artist", "en", "Kunstneren maler et bilde.", "The artist paints a picture."),
    ("forfatter", "author", "en", "Forfatteren skriver en ny bok.", "The author is writing a new book."),
    ("student", "student", "en", "Studenten leser til eksamen.", "The student studies for the exam."),
    ("konge", "king", "en", "Kongen bor i slottet.", "The king lives in the castle."),
    ("dronning", "queen", "ei", "Dronninga holdt en tale.", "The queen gave a speech."),
    ("gjest", "guest", "en", "Vi har gjester i kveld.", "We have guests tonight."),
    ("person", "person", "en", "Hun er en hyggelig person.", "She is a nice person."),
    ("folk", "people", "et", "Det er mye folk i byen.", "There are a lot of people in the city."),
    # --- time & abstract ---
    ("tid", "time", "ei", "Jeg har ikke tid i dag.", "I don't have time today."),
    ("øyeblikk", "moment", "et", "Vent et øyeblikk.", "Wait a moment."),
    ("liv", "life", "et", "Livet er kort.", "Life is short."),
    ("verden", "world", "en", "Verden er stor.", "The world is big."),
    ("historie", "story/history", "ei", "Han fortalte en morsom historie.", "He told a funny story."),
    ("sannhet", "truth", "en", "Du må fortelle sannheten.", "You have to tell the truth."),
    ("løgn", "lie", "en", "Det er en løgn.", "That is a lie."),
    ("idé", "idea", "en", "Jeg har en god idé.", "I have a good idea."),
    ("problem", "problem", "et", "Vi har et stort problem.", "We have a big problem."),
    ("løsning", "solution", "ei", "Vi fant en løsning.", "We found a solution."),
    ("grunn", "reason", "en", "Det er ingen grunn til å gråte.", "There is no reason to cry."),
    ("følelse", "feeling", "en", "Jeg har en god følelse.", "I have a good feeling."),
    ("drøm", "dream", "en", "Jeg hadde en rar drøm.", "I had a strange dream."),
    ("plan", "plan", "en", "Hva er planen for i dag?", "What is the plan for today?"),
    ("sjanse", "chance", "en", "Gi meg en sjanse.", "Give me a chance."),
    ("feil", "mistake", "en", "Alle gjør feil.", "Everyone makes mistakes."),
    ("musikk", "music", "en", "Jeg elsker å høre på musikk.", "I love listening to music."),
    ("sang", "song", "en", "Dette er favorittsangen min.", "This is my favorite song."),
    ("film", "film", "en", "Filmen var spennende.", "The film was exciting."),
    ("spill", "game", "et", "Barna liker dette spillet.", "The children like this game."),
    ("ferie", "holiday", "en", "Vi gleder oss til ferien.", "We are looking forward to the holiday."),
    ("fest", "party", "en", "Vi skal på fest i kveld.", "We are going to a party tonight."),
    ("gave", "gift", "en", "Jeg kjøpte en gave til henne.", "I bought a gift for her."),
    ("bursdag", "birthday", "en", "Det er bursdagen min i dag.", "It is my birthday today."),
    ("regning", "bill", "ei", "Kan jeg få regninga?", "Can I have the bill?"),
    ("pris", "price", "en", "Prisen er for høy.", "The price is too high."),
    ("brev", "letter", "et", "Jeg fikk et brev i posten.", "I got a letter in the mail."),
    ("avis", "newspaper", "ei", "Han leser avisa hver morgen.", "He reads the newspaper every morning."),
    ("nyhet", "news", "en", "Har du hørt nyheten?", "Have you heard the news?"),
    ("melding", "message", "ei", "Jeg sendte deg en melding.", "I sent you a message."),
    ("datamaskin", "computer", "en", "Datamaskinen er treg.", "The computer is slow."),
    ("internett", "internet", "et", "Vi har ikke internett i dag.", "We don't have internet today."),
    ("skjerm", "screen", "en", "Skjermen er for lys.", "The screen is too bright."),
    ("kamera", "camera", "et", "Kameraet tar fine bilder.", "The camera takes nice pictures."),
    ("nummer", "number", "et", "Hva er telefonnummeret ditt?", "What is your phone number?"),
    ("bokstav", "letter (alphabet)", "en", "Hvilken bokstav er dette?", "Which letter is this?"),
    ("setning", "sentence", "ei", "Skriv en hel setning.", "Write a whole sentence."),
    ("eksamen", "exam", "en", "Eksamen er på fredag.", "The exam is on Friday."),
    ("leksjon", "lesson", "en", "Dagens leksjon er vanskelig.", "Today's lesson is difficult."),
    ("oppgave", "task", "ei", "Oppgava er ikke ferdig.", "The task is not finished."),
    ("kjærlighet", "love", "en", "Kjærlighet er viktig.", "Love is important."),
    ("vennskap", "friendship", "et", "Vennskap varer lenge.", "Friendship lasts a long time."),
    ("helse", "health", "ei", "Helsa er det viktigste.", "Health is the most important thing."),
    ("medisin", "medicine", "en", "Ta medisinen to ganger om dagen.", "Take the medicine twice a day."),
    ("kropp", "body", "en", "Søvn er bra for kroppen.", "Sleep is good for the body."),
    ("sport", "sport", "en", "Fotball er en populær sport.", "Football is a popular sport."),
    ("lag", "team", "et", "Laget vant kampen.", "The team won the match."),
    ("kamp", "match", "en", "Kampen begynner klokka åtte.", "The match begins at eight o'clock."),
    ("ball", "ball", "en", "Gutten sparker ballen.", "The boy kicks the ball."),
    ("tur", "trip/walk", "en", "Vi går en tur i skogen.", "We go for a walk in the forest."),
]

VERBS_B = [
    ("åpne", "open", "Hun åpner gaven sin.", "She opens her gift."),
    ("sove", "sleep", "Barnet sover hele natta.", "The child sleeps all night."),
    ("våkne", "wake up", "Jeg våkner klokka sju.", "I wake up at seven o'clock."),
    ("stå opp", "get up", "Jeg står opp tidlig.", "I get up early."),
    ("legge seg", "go to bed", "Barna legger seg klokka åtte.", "The children go to bed at eight o'clock."),
    ("kle på seg", "get dressed", "Han kler på seg fort.", "He gets dressed quickly."),
    ("dusje", "shower", "Jeg dusjer hver morgen.", "I shower every morning."),
    ("pusse tenner", "brush teeth", "Husk å pusse tenner.", "Remember to brush your teeth."),
    ("vaske", "wash", "Jeg vasker klærne på lørdag.", "I wash the clothes on Saturday."),
    ("rydde", "tidy up", "Vi må rydde rommet.", "We have to tidy up the room."),
    ("koke", "boil", "Jeg koker vann til te.", "I boil water for tea."),
    ("steke", "fry", "Hun steker egg til frokost.", "She fries eggs for breakfast."),
    ("bake", "bake", "Vi baker brød hjemme.", "We bake bread at home."),
    ("smake", "taste", "Maten smaker godt.", "The food tastes good."),
    ("lukte", "smell", "Blomstene lukter deilig.", "The flowers smell lovely."),
    ("kaste", "throw", "Ikke kast søppel på bakken.", "Don't throw rubbish on the ground."),
    ("fange", "catch", "Hunden fanger ballen.", "The dog catches the ball."),
    ("hoppe", "jump", "Barna hopper på senga.", "The children jump on the bed."),
    ("klatre", "climb", "Katten klatrer opp i treet.", "The cat climbs up the tree."),
    ("falle", "fall", "Pass på så du ikke faller.", "Be careful not to fall."),
    ("gå tur", "go for a walk", "Vi går tur hver dag.", "We go for a walk every day."),
    ("sykle", "cycle", "Jeg sykler til jobben.", "I cycle to work."),
    ("fly", "fly", "Fuglene flyr sørover om høsten.", "The birds fly south in autumn."),
    ("seile", "sail", "De seiler langs kysten.", "They sail along the coast."),
    ("gå av", "get off", "Jeg går av bussen her.", "I get off the bus here."),
    ("gå på", "get on", "Vi går på toget klokka ni.", "We get on the train at nine o'clock."),
    ("vinne", "win", "Laget vårt vant kampen.", "Our team won the match."),
    ("tape", "lose (a game)", "Vi tapte dessverre.", "We lost, unfortunately."),
    ("trene", "exercise", "Jeg trener tre ganger i uka.", "I exercise three times a week."),
    ("hvile", "rest", "Du må hvile når du er syk.", "You have to rest when you are sick."),
    ("puste", "breathe", "Pust dypt inn.", "Breathe in deeply."),
    ("gjemme", "hide", "Barna gjemmer seg bak sofaen.", "The children hide behind the sofa."),
    ("søke", "search", "Jeg søker etter jobb.", "I am searching for a job."),
    ("leie", "rent", "De leier en leilighet.", "They rent an apartment."),
    ("eie", "own", "Vi eier et lite hus.", "We own a small house."),
    ("låne", "borrow/lend", "Kan jeg låne pengene dine?", "Can I borrow your money?"),
    ("spare", "save", "Jeg sparer penger til en ferie.", "I save money for a holiday."),
    ("koste", "cost", "Hvor mye koster det?", "How much does it cost?"),
    ("tjene", "earn", "Han tjener mye penger.", "He earns a lot of money."),
    ("bestille", "order", "Vi bestiller pizza i kveld.", "We are ordering pizza tonight."),
    ("smile", "smile", "Hun smiler til meg.", "She smiles at me."),
    ("gjenta", "repeat", "Kan du gjenta det?", "Can you repeat that?"),
    ("oversette", "translate", "Kan du oversette dette?", "Can you translate this?"),
    ("stave", "spell", "Hvordan staver du navnet ditt?", "How do you spell your name?"),
    ("telle", "count", "Barnet teller til ti.", "The child counts to ten."),
    ("regne", "calculate", "Jeg regner ut prisen.", "I calculate the price."),
    ("studere", "study", "Hun studerer medisin.", "She studies medicine."),
    ("undervise", "teach", "Han underviser i norsk.", "He teaches Norwegian."),
    ("øve", "practice", "Jeg øver på norsk hver dag.", "I practice Norwegian every day."),
    ("prøve", "try", "Prøv en gang til.", "Try one more time."),
    ("klare", "manage", "Jeg klarer det selv.", "I can manage it myself."),
    ("greie", "handle", "Vi greier dette sammen.", "We'll handle this together."),
    ("lykkes", "succeed", "Han lyktes med planen.", "He succeeded with the plan."),
    ("mislykkes", "fail", "Forsøket mislyktes.", "The attempt failed."),
    ("bestemme", "decide", "Vi må bestemme oss nå.", "We have to decide now."),
    ("velge", "choose", "Velg en farge.", "Choose a color."),
    ("foreslå", "suggest", "Jeg foreslår at vi går.", "I suggest that we leave."),
    ("love", "promise", "Jeg lover å komme.", "I promise to come."),
    ("nekte", "refuse", "Han nekter å hjelpe.", "He refuses to help."),
    ("tillate", "allow", "Foreldrene tillater det ikke.", "The parents don't allow it."),
    ("forby", "forbid", "Det er forbudt å røyke her.", "It is forbidden to smoke here."),
    ("møtes", "meet (each other)", "Vi møtes på kafeen.", "We meet at the café."),
    ("besøke", "visit", "Vi besøker bestemor på søndag.", "We visit grandma on Sunday."),
    ("invitere", "invite", "Jeg inviterer deg til fest.", "I invite you to a party."),
    ("feire", "celebrate", "Vi feirer bursdagen hennes.", "We are celebrating her birthday."),
    ("danse", "dance", "De danser hele natta.", "They dance all night."),
    ("lytte", "listen", "Lytt nøye.", "Listen carefully."),
    ("se på", "watch", "Vi ser på en film.", "We are watching a film."),
    ("kjenne", "know (a person)", "Jeg kjenner ham godt.", "I know him well."),
    ("treffe", "meet", "Jeg traff en gammel venn.", "I met an old friend."),
    ("hilse", "greet", "Hils på naboen.", "Say hello to the neighbor."),
    ("takke", "thank", "Jeg vil takke deg for hjelpen.", "I want to thank you for the help."),
    ("beklage", "apologize", "Jeg beklager forsinkelsen.", "I apologize for the delay."),
    ("krangle", "argue", "De krangler ofte.", "They argue often."),
    ("slåss", "fight", "Guttene slåss på skolen.", "The boys fight at school."),
    ("hjelpe til", "help out", "Kan du hjelpe til hjemme?", "Can you help out at home?"),
    ("dele", "share", "Vi deler maten.", "We share the food."),
    ("gi bort", "give away", "Hun ga bort de gamle klærne.", "She gave away the old clothes."),
    ("motta", "receive", "Jeg mottok pakken i dag.", "I received the package today."),
    ("åpne opp", "open up", "Han åpnet opp om følelsene sine.", "He opened up about his feelings."),
    ("lukke igjen", "close", "Lukk igjen vinduet.", "Close the window."),
    ("slå på", "turn on", "Slå på lyset.", "Turn on the light."),
    ("slå av", "turn off", "Slå av TV-en.", "Turn off the TV."),
    ("fylle", "fill", "Fyll glasset med vann.", "Fill the glass with water."),
    ("tømme", "empty", "Jeg tømmer søpla.", "I empty the rubbish."),
    ("flytte", "move", "Vi flytter til Bergen.", "We are moving to Bergen."),
    ("reparere", "repair", "Han reparerer sykkelen.", "He is repairing the bike."),
    ("ødelegge", "destroy/break", "Ikke ødelegg leketøyet.", "Don't break the toy."),
    ("fungere", "work (function)", "Telefonen fungerer ikke.", "The phone doesn't work."),
    ("vente på", "wait for", "Jeg venter på bussen.", "I am waiting for the bus."),
    ("skynde seg", "hurry", "Skynd deg, vi er sene!", "Hurry up, we are late!"),
    ("stoppe", "stop", "Bilen stoppet plutselig.", "The car stopped suddenly."),
    ("fortsette", "continue", "La oss fortsette i morgen.", "Let's continue tomorrow."),
    ("endre", "change", "Jeg vil endre planen.", "I want to change the plan."),
    ("vokse", "grow", "Barna vokser fort.", "The children grow fast."),
    ("regne", "rain", "Det regner ute.", "It is raining outside."),
    ("snø", "snow", "Det snør i fjellet.", "It is snowing in the mountains."),
    ("skinne", "shine", "Sola skinner i dag.", "The sun is shining today."),
    ("fryse", "freeze/be cold", "Jeg fryser om hendene.", "My hands are cold."),
    ("svette", "sweat", "Jeg svetter når jeg trener.", "I sweat when I exercise."),
    ("gråte", "weep", "Hun gråt av glede.", "She wept with joy."),
    ("smake på", "taste (sample)", "Vil du smake på kaka?", "Do you want to taste the cake?"),
    ("røyke", "smoke", "Det er ikke lov å røyke her.", "It is not allowed to smoke here."),
    ("drømme", "dream", "Jeg drømmer hver natt.", "I dream every night."),
    ("savne", "miss", "Jeg savner familien min.", "I miss my family."),
    ("gle seg", "look forward to", "Jeg gleder meg til ferien.", "I am looking forward to the holiday."),
    ("bekymre seg", "worry", "Ikke bekymre deg.", "Don't worry."),
    ("stole på", "trust", "Jeg stoler på deg.", "I trust you."),
    ("mene", "mean/think", "Hva mener du?", "What do you mean?"),
    ("synes", "think/feel", "Jeg synes filmen var bra.", "I think the film was good."),
    ("anbefale", "recommend", "Jeg anbefaler denne boka.", "I recommend this book."),
    ("forklare", "explain", "Kan du forklare det?", "Can you explain it?"),
    ("fortelle", "tell", "Fortell meg om dagen din.", "Tell me about your day."),
    ("snakke om", "talk about", "Vi snakker om været.", "We are talking about the weather."),
    ("bety", "mean", "Hva betyr dette ordet?", "What does this word mean?"),
    ("kalle", "call (name)", "De kaller ham Ola.", "They call him Ola."),
    ("vise frem", "show off", "Hun viser frem den nye kjolen.", "She shows off her new dress."),
]

ADJECTIVES_B = [
    ("ung", "young", "Hun er fortsatt ung.", "She is still young."),
    ("middels", "medium", "Jeg vil ha en middels stor kaffe.", "I want a medium-sized coffee."),
    ("bred", "wide", "Elva er bred her.", "The river is wide here."),
    ("smal", "narrow", "Gata er veldig smal.", "The street is very narrow."),
    ("dyp", "deep", "Vannet er dypt her.", "The water is deep here."),
    ("grunn", "shallow", "Bassenget er grunt for barna.", "The pool is shallow for the children."),
    ("tykk", "thick", "Boka er tykk.", "The book is thick."),
    ("tynn", "thin", "Isen er for tynn.", "The ice is too thin."),
    ("hard", "hard", "Senga er for hard.", "The bed is too hard."),
    ("myk", "soft", "Puta er myk.", "The pillow is soft."),
    ("glatt", "slippery", "Veien er glatt om vinteren.", "The road is slippery in winter."),
    ("våt", "wet", "Klærne er våte.", "The clothes are wet."),
    ("tørr", "dry", "Håndkleet er tørt nå.", "The towel is dry now."),
    ("lys", "light/bright", "Rommet er lyst og fint.", "The room is bright and nice."),
    ("mørk", "dark", "Det er mørkt ute nå.", "It is dark outside now."),
    ("stygg", "ugly", "Været er stygt i dag.", "The weather is nasty today."),
    ("søt", "sweet/cute", "Kaka er for søt.", "The cake is too sweet."),
    ("sur", "sour", "Sitronen er sur.", "The lemon is sour."),
    ("bitter", "bitter", "Kaffen er bitter.", "The coffee is bitter."),
    ("salt", "salty", "Suppa er for salt.", "The soup is too salty."),
    ("fersk", "fresh", "Brødet er ferskt.", "The bread is fresh."),
    ("råtten", "rotten", "Eplet er råttent.", "The apple is rotten."),
    ("moden", "ripe", "Bananen er moden.", "The banana is ripe."),
    ("rik", "rich", "De er veldig rike.", "They are very rich."),
    ("fattig", "poor", "Familien var fattig.", "The family was poor."),
    ("gratis", "free (no cost)", "Inngangen er gratis.", "The entrance is free."),
    ("ekte", "real/genuine", "Dette er ekte gull.", "This is real gold."),
    ("falsk", "fake", "Pengene var falske.", "The money was fake."),
    ("enkel", "simple", "Oppskriften er enkel.", "The recipe is simple."),
    ("vanlig", "usual/common", "Det er et vanlig navn.", "It is a common name."),
    ("spesiell", "special", "I dag er en spesiell dag.", "Today is a special day."),
    ("annerledes", "different", "Denne er litt annerledes.", "This one is a bit different."),
    ("lik", "alike/similar", "De to husene er like.", "The two houses are alike."),
    ("ekte", "true", "Det er ekte vennskap.", "It is true friendship."),
    ("sann", "true", "Er det sant?", "Is it true?"),
    ("usann", "false", "Påstanden er usann.", "The claim is false."),
    ("mulig", "possible", "Er det mulig?", "Is it possible?"),
    ("umulig", "impossible", "Det er nesten umulig.", "It is almost impossible."),
    ("nødvendig", "necessary", "Det er ikke nødvendig.", "It is not necessary."),
    ("ferdig", "finished", "Er du ferdig med leksene?", "Are you finished with the homework?"),
    ("klar", "ready", "Maten er klar.", "The food is ready."),
    ("opptatt", "busy", "Linja er opptatt.", "The line is busy."),
    ("ledig", "available/vacant", "Er dette setet ledig?", "Is this seat available?"),
    ("åpen", "open", "Butikken er åpen.", "The shop is open."),
    ("stengt", "closed", "Banken er stengt i dag.", "The bank is closed today."),
    ("trygg", "safe", "Her er det trygt.", "It is safe here."),
    ("farlig", "dangerous", "Det er farlig å kjøre fort.", "It is dangerous to drive fast."),
    ("interessant", "interesting", "Boka er interessant.", "The book is interesting."),
    ("vennlig", "friendly", "Naboen er veldig vennlig.", "The neighbor is very friendly."),
    ("høflig", "polite", "Han er alltid høflig.", "He is always polite."),
    ("uhøflig", "rude", "Det var uhøflig sagt.", "That was rudely said."),
    ("ærlig", "honest", "Vær ærlig med meg.", "Be honest with me."),
    ("lat", "lazy", "Katten er lat.", "The cat is lazy."),
    ("flink", "skilled/good at", "Hun er flink til å tegne.", "She is good at drawing."),
    ("dum", "stupid", "Det var et dumt spørsmål.", "That was a stupid question."),
    ("smart", "smart", "Det var en smart løsning.", "That was a smart solution."),
    ("klok", "wise", "Bestemor er klok.", "Grandma is wise."),
    ("gal", "crazy", "Er du gal?", "Are you crazy?"),
    ("nervøs", "nervous", "Jeg er nervøs før eksamen.", "I am nervous before the exam."),
    ("sint", "angry", "Hvorfor er du sint?", "Why are you angry?"),
    ("fornøyd", "satisfied", "Jeg er fornøyd med resultatet.", "I am satisfied with the result."),
    ("skuffet", "disappointed", "Jeg er litt skuffet.", "I am a little disappointed."),
    ("overrasket", "surprised", "Jeg ble veldig overrasket.", "I was very surprised."),
    ("stolt", "proud", "Jeg er stolt av deg.", "I am proud of you."),
    ("flau", "embarrassed", "Jeg ble flau.", "I got embarrassed."),
    ("forelsket", "in love", "Han er forelsket i henne.", "He is in love with her."),
    ("ensom", "lonely", "Hun føler seg ensom.", "She feels lonely."),
    ("spent", "excited/tense", "Jeg er spent på resultatet.", "I am excited about the result."),
    ("rar", "strange", "Det smaker litt rart.", "It tastes a little strange."),
    ("vått", "soaked", "Vi ble våte i regnet.", "We got soaked in the rain."),
    ("nydelig", "lovely", "For en nydelig dag!", "What a lovely day!"),
    ("forsiktig", "careful", "Vær forsiktig!", "Be careful!"),
    ("sjenert", "shy", "Gutten er litt sjenert.", "The boy is a bit shy."),
    ("populær", "popular", "Sangen er veldig populær.", "The song is very popular."),
    ("berømt", "famous", "Han er en berømt skuespiller.", "He is a famous actor."),
    ("moderne", "modern", "Huset er moderne.", "The house is modern."),
    ("gammeldags", "old-fashioned", "Telefonen er gammeldags.", "The phone is old-fashioned."),
    ("hel", "whole", "Jeg spiste en hel pizza.", "I ate a whole pizza."),
    ("halv", "half", "Klokka er halv to.", "It is half past one."),
    ("neste", "next", "Vi går av på neste stopp.", "We get off at the next stop."),
    ("forrige", "previous", "Forrige uke var travel.", "Last week was busy."),
    ("samme", "same", "Vi bor i samme by.", "We live in the same city."),
    ("egen", "own", "Jeg har mitt eget rom.", "I have my own room."),
]

OTHER_B = [
    ("dere", "you (plural)", "pronoun", "Hvor skal dere?", "Where are you all going?"),
    ("det", "it", "pronoun", "Det er kaldt i dag.", "It is cold today."),
    ("den", "it/that", "pronoun", "Den er fin.", "That one is nice."),
    ("denne", "this", "pronoun", "Jeg liker denne.", "I like this one."),
    ("alle", "everyone/all", "pronoun", "Alle er her nå.", "Everyone is here now."),
    ("noen", "someone/some", "pronoun", "Er det noen hjemme?", "Is anyone home?"),
    ("ingen", "no one", "pronoun", "Ingen vet svaret.", "No one knows the answer."),
    ("alt", "everything", "pronoun", "Alt er bra.", "Everything is fine."),
    ("noe", "something", "pronoun", "Jeg vil ha noe å spise.", "I want something to eat."),
    ("ingenting", "nothing", "pronoun", "Jeg ser ingenting.", "I see nothing."),
    ("hverandre", "each other", "pronoun", "Vi hjelper hverandre.", "We help each other."),
    ("selv", "myself/oneself", "pronoun", "Jeg gjør det selv.", "I do it myself."),
    ("min", "my/mine", "pronoun", "Det er boka mi.", "That is my book."),
    ("din", "your/yours", "pronoun", "Er dette din jakke?", "Is this your jacket?"),
    ("vår", "our/ours", "pronoun", "Det er huset vårt.", "That is our house."),
    ("etter", "after", "preposition", "Vi spiser etter filmen.", "We eat after the film."),
    ("før", "before", "preposition", "Kom hjem før mørket.", "Come home before dark."),
    ("mellom", "between", "preposition", "Butikken ligger mellom to hus.", "The shop is between two houses."),
    ("ved", "by/at", "preposition", "Hun sitter ved vinduet.", "She sits by the window."),
    ("hos", "at (someone's)", "preposition", "Jeg er hos legen.", "I am at the doctor's."),
    ("om", "about/in", "preposition", "Vi snakker om filmen.", "We are talking about the film."),
    ("mot", "against/towards", "preposition", "Han gikk mot døra.", "He walked towards the door."),
    ("gjennom", "through", "preposition", "Vi kjørte gjennom byen.", "We drove through the city."),
    ("rundt", "around", "preposition", "Vi gikk rundt sjøen.", "We walked around the lake."),
    ("bak", "behind", "preposition", "Hagen ligger bak huset.", "The garden is behind the house."),
    ("foran", "in front of", "preposition", "Bilen står foran huset.", "The car is in front of the house."),
    ("ut", "out", "adverb", "La oss gå ut.", "Let's go out."),
    ("inn", "in", "adverb", "Kom inn!", "Come in!"),
    ("opp", "up", "adverb", "Se opp!", "Look up!"),
    ("ned", "down", "adverb", "Sett deg ned.", "Sit down."),
    ("hjemme", "at home", "adverb", "Jeg er hjemme i dag.", "I am at home today."),
    ("ute", "outside", "adverb", "Barna leker ute.", "The children play outside."),
    ("inne", "inside", "adverb", "Det er varmt inne.", "It is warm inside."),
    ("snart", "soon", "adverb", "Vi er snart framme.", "We will arrive soon."),
    ("allerede", "already", "adverb", "Han har allerede gått.", "He has already left."),
    ("ennå", "yet/still", "adverb", "Jeg er ikke ferdig ennå.", "I am not finished yet."),
    ("igjen", "again", "adverb", "Prøv igjen.", "Try again."),
    ("også", "also", "adverb", "Jeg vil også være med.", "I want to come too."),
    ("bare", "only/just", "adverb", "Jeg vil bare hjelpe.", "I only want to help."),
    ("nesten", "almost", "adverb", "Jeg er nesten ferdig.", "I am almost done."),
    ("ganske", "quite", "adverb", "Det er ganske kaldt.", "It is quite cold."),
    ("for", "too", "adverb", "Det er for dyrt.", "It is too expensive."),
    ("sammen", "together", "adverb", "Vi gjør det sammen.", "We do it together."),
    ("fort", "quickly", "adverb", "Kom fort!", "Come quickly!"),
    ("sakte", "slowly", "adverb", "Kjør sakte her.", "Drive slowly here."),
    ("kanskje", "perhaps", "adverb", "Kanskje vi ses i morgen.", "Perhaps we'll see each other tomorrow."),
    ("dessverre", "unfortunately", "adverb", "Dessverre kan jeg ikke komme.", "Unfortunately I can't come."),
    ("heldigvis", "fortunately", "adverb", "Heldigvis sluttet det å regne.", "Fortunately it stopped raining."),
    ("derfor", "therefore", "conjunction", "Det regnet, derfor ble vi hjemme.", "It rained, therefore we stayed home."),
    ("hvis", "if", "conjunction", "Hvis det regner, blir vi inne.", "If it rains, we stay inside."),
    ("når", "when", "conjunction", "Ring meg når du kommer.", "Call me when you arrive."),
    ("at", "that", "conjunction", "Jeg vet at du har rett.", "I know that you are right."),
    ("som", "as/that/who", "conjunction", "Mannen som bor her, er snill.", "The man who lives here is kind."),
    ("elleve", "eleven", "number", "Klokka er elleve.", "It is eleven o'clock."),
    ("tjue", "twenty", "number", "Hun er tjue år gammel.", "She is twenty years old."),
    ("hundre", "hundred", "number", "Det koster hundre kroner.", "It costs one hundred kroner."),
    ("tusen", "thousand", "number", "Tusen takk!", "A thousand thanks!"),
    ("første", "first", "number", "Det er min første dag.", "It is my first day."),
    ("andre", "second", "number", "Dette er andre gang.", "This is the second time."),
    ("siste", "last", "number", "Dette er siste sjanse.", "This is the last chance."),
]

PHRASES_B = [
    ("God natt!", "Good night!"),
    ("Ha en fin helg!", "Have a nice weekend!"),
    ("Velkommen!", "Welcome!"),
    ("Lenge siden sist!", "Long time no see!"),
    ("Hvor kommer du fra?", "Where are you from?"),
    ("Hvor gammel er du?", "How old are you?"),
    ("Hva jobber du med?", "What do you do for work?"),
    ("Hva liker du å gjøre?", "What do you like to do?"),
    ("Jeg vet ikke ennå.", "I don't know yet."),
    ("Det høres bra ut.", "That sounds good."),
    ("Det er greit.", "That's fine."),
    ("Ikke noe problem.", "No problem at all."),
    ("Selvfølgelig!", "Of course!"),
    ("Det stemmer.", "That's right."),
    ("Jeg er ikke sikker.", "I am not sure."),
    ("Kanskje senere.", "Maybe later."),
    ("Ett øyeblikk, takk.", "One moment, please."),
    ("Kan du hjelpe meg?", "Can you help me?"),
    ("Hvor er nærmeste butikk?", "Where is the nearest shop?"),
    ("Hvor langt er det?", "How far is it?"),
    ("Når åpner det?", "When does it open?"),
    ("Når stenger det?", "When does it close?"),
    ("Hva er klokka?", "What time is it?"),
    ("Klokka er tre.", "It is three o'clock."),
    ("Jeg er litt forsinket.", "I am a little late."),
    ("Vi sees i morgen.", "See you tomorrow."),
    ("Snakkes snart!", "Talk to you soon!"),
    ("Kos deg!", "Enjoy yourself!"),
    ("Lykke til!", "Good luck!"),
    ("God bedring!", "Get well soon!"),
    ("Skål!", "Cheers!"),
    ("Vær så god, sett deg.", "Please, have a seat."),
    ("Kan jeg betale med kort?", "Can I pay by card?"),
    ("Har du veksel?", "Do you have change?"),
    ("Hvor mye blir det?", "How much will that be?"),
    ("Det var alt, takk.", "That's all, thank you."),
    ("Jeg tar denne.", "I'll take this one."),
    ("Kan jeg prøve den?", "Can I try it on?"),
    ("Har dere den i en større størrelse?", "Do you have it in a larger size?"),
    ("Jeg ser meg bare litt rundt.", "I'm just looking around."),
    ("Unnskyld, hvor er toalettet?", "Excuse me, where is the toilet?"),
    ("Jeg forstår litt norsk.", "I understand a little Norwegian."),
    ("Snakk litt saktere, takk.", "Speak a little more slowly, please."),
    ("Hva heter dette på norsk?", "What is this called in Norwegian?"),
    ("Jeg har bodd her i to år.", "I have lived here for two years."),
    ("Vi snakkes!", "We'll talk!"),
    ("Ta vare på deg selv.", "Take care of yourself."),
    ("Det går bra.", "It's going well."),
    ("Jeg er sulten.", "I am hungry."),
    ("Jeg er trøtt.", "I am tired."),
]

# ===========================================================================
# BATCH C — final top-up to ~1000 cards
# ===========================================================================

NOUNS_C = [
    # --- more everyday objects ---
    ("flaske", "bottle", "ei", "Flaska er full av vann.", "The bottle is full of water."),
    ("eske", "box", "ei", "Eska er tom.", "The box is empty."),
    ("pose", "bag (plastic)", "en", "Jeg trenger en pose til varene.", "I need a bag for the groceries."),
    ("koffert", "suitcase", "en", "Kofferten er tung.", "The suitcase is heavy."),
    ("paraply", "umbrella", "en", "Husk paraplyen, det regner.", "Remember the umbrella, it's raining."),
    ("saks", "scissors", "ei", "Kan jeg låne saksa?", "Can I borrow the scissors?"),
    ("penn", "pen", "en", "Pennen min er tom.", "My pen is out of ink."),
    ("viskelær", "eraser", "et", "Bruk viskelæret.", "Use the eraser."),
    ("kalender", "calendar", "en", "Skriv det i kalenderen.", "Write it in the calendar."),
    ("verktøy", "tool", "et", "Jeg trenger riktig verktøy.", "I need the right tool."),
    ("hammer", "hammer", "en", "Han slår spikeren med en hammer.", "He hits the nail with a hammer."),
    ("spiker", "nail", "en", "Spikeren er for kort.", "The nail is too short."),
    ("tråd", "thread", "en", "Tråden er rød.", "The thread is red."),
    ("nål", "needle", "ei", "Pass deg for nåla.", "Watch out for the needle."),
    ("knapp", "button", "en", "En knapp falt av jakka.", "A button fell off the jacket."),
    ("lommebok", "wallet", "ei", "Jeg glemte lommeboka hjemme.", "I forgot my wallet at home."),
    ("sekk", "backpack", "en", "Sekken er full av bøker.", "The backpack is full of books."),
    ("leketøy", "toy", "et", "Barnet leker med leketøyet.", "The child plays with the toy."),
    ("dukke", "doll", "ei", "Jenta har en fin dukke.", "The girl has a nice doll."),
    ("batteri", "battery", "et", "Batteriet er tomt.", "The battery is dead."),
    # --- more food ---
    ("ris", "rice", "en", "Vi spiser ris til middag.", "We eat rice for dinner."),
    ("pasta", "pasta", "en", "Barna elsker pasta.", "The children love pasta."),
    ("mel", "flour", "et", "Jeg trenger mel til kaka.", "I need flour for the cake."),
    ("honning", "honey", "en", "Jeg liker honning på brødet.", "I like honey on my bread."),
    ("syltetøy", "jam", "et", "Hun har syltetøy på skiva.", "She has jam on her slice of bread."),
    ("pølse", "sausage", "ei", "Vi griller pølser ute.", "We grill sausages outside."),
    ("kylling", "chicken", "en", "Vi spiser kylling i kveld.", "We are eating chicken tonight."),
    ("skinke", "ham", "ei", "Han la skinke på brødet.", "He put ham on the bread."),
    ("nøtt", "nut", "ei", "Jeg er allergisk mot nøtter.", "I am allergic to nuts."),
    ("kjeks", "biscuit", "en", "Vil du ha en kjeks?", "Do you want a biscuit?"),
    ("bolle", "bun", "en", "Vi kjøpte ferske boller.", "We bought fresh buns."),
    ("smørbrød", "sandwich", "et", "Jeg lager et smørbrød.", "I am making a sandwich."),
    ("drikke", "drink", "en", "Hva slags drikke vil du ha?", "What kind of drink would you like?"),
    ("måltid", "meal", "et", "Dette var et godt måltid.", "This was a good meal."),
    # --- time words ---
    ("i dag", "today", "en", "I dag er det fint vær.", "Today the weather is nice."),
    ("i går", "yesterday", "en", "I går regnet det.", "Yesterday it rained."),
    ("i morgen", "tomorrow", "en", "I morgen drar vi på tur.", "Tomorrow we are going on a trip."),
    ("helg", "weekend", "ei", "Hva skal du gjøre i helga?", "What are you doing this weekend?"),
    ("ferie", "vacation", "en", "Sommerferien begynner snart.", "The summer vacation begins soon."),
    ("fødselsdag", "birthday", "en", "Når har du fødselsdag?", "When is your birthday?"),
    ("jul", "Christmas", "ei", "Vi feirer jul med familien.", "We celebrate Christmas with the family."),
    ("påske", "Easter", "ei", "I påsken går vi på ski.", "At Easter we go skiing."),
    # --- weekdays & months (handy as nouns) ---
    ("mandag", "Monday", "en", "Jeg jobber fra mandag til fredag.", "I work from Monday to Friday."),
    ("tirsdag", "Tuesday", "en", "Vi har norsktime på tirsdag.", "We have Norwegian class on Tuesday."),
    ("onsdag", "Wednesday", "en", "Onsdag er midt i uka.", "Wednesday is the middle of the week."),
    ("torsdag", "Thursday", "en", "På torsdag spiller vi fotball.", "On Thursday we play football."),
    ("fredag", "Friday", "en", "Endelig er det fredag!", "Finally it's Friday!"),
    ("lørdag", "Saturday", "en", "På lørdag sover jeg lenge.", "On Saturday I sleep in."),
    ("søndag", "Sunday", "en", "Søndag er en rolig dag.", "Sunday is a quiet day."),
    # --- people & relationships ---
    ("bestemor", "grandmother", "ei", "Bestemor baker de beste bollene.", "Grandma bakes the best buns."),
    ("bestefar", "grandfather", "en", "Bestefar forteller gamle historier.", "Grandpa tells old stories."),
    ("datter", "daughter", "ei", "Dattera deres heter Kari.", "Their daughter's name is Kari."),
    ("sønn", "son", "en", "Sønnen min går på skolen.", "My son goes to school."),
    ("tante", "aunt", "ei", "Tanta mi bor i Trondheim.", "My aunt lives in Trondheim."),
    ("onkel", "uncle", "en", "Onkelen min er fisker.", "My uncle is a fisherman."),
    ("kjæreste", "partner/boyfriend/girlfriend", "en", "Dette er kjæresten min.", "This is my partner."),
    ("ektemann", "husband", "en", "Ektemannen hennes lager mat.", "Her husband cooks."),
    ("kone", "wife", "ei", "Kona hans er lege.", "His wife is a doctor."),
    ("voksen", "adult", "en", "En voksen må følge med barnet.", "An adult must accompany the child."),
    ("ungdom", "youth/teenager", "en", "Ungdommen spiller fotball.", "The teenager plays football."),
    # --- abstract / useful ---
    ("hjelp", "help", "ei", "Takk for hjelpen!", "Thanks for the help!"),
    ("ro", "peace/quiet", "en", "Jeg trenger litt ro.", "I need a little quiet."),
    ("stillhet", "silence", "en", "Det var helt stille i rommet.", "It was completely silent in the room."),
    ("lyd", "sound", "en", "Hva var den lyden?", "What was that sound?"),
    ("lys", "light", "et", "Slå på lyset, takk.", "Turn on the light, please."),
    ("skygge", "shadow/shade", "en", "Vi sitter i skyggen.", "We sit in the shade."),
    ("varme", "heat/warmth", "en", "Varmen fra peisen er god.", "The warmth from the fireplace is nice."),
    ("kulde", "cold", "en", "Kulda biter i kinnene.", "The cold bites at the cheeks."),
    ("kraft", "power/force", "ei", "Vinden hadde stor kraft.", "The wind had great force."),
    ("retning", "direction", "ei", "Vi går i feil retning.", "We are going in the wrong direction."),
    ("avstand", "distance", "en", "Avstanden er for stor.", "The distance is too great."),
    ("størrelse", "size", "en", "Hvilken størrelse bruker du?", "What size do you use?"),
    ("vekt", "weight", "ei", "Vekta viser sytti kilo.", "The scale shows seventy kilos."),
    ("høyde", "height", "en", "Hva er høyden på fjellet?", "What is the height of the mountain?"),
    ("del", "part", "en", "Dette er den beste delen.", "This is the best part."),
    ("slutt", "end", "en", "Vi er nær slutten.", "We are near the end."),
    ("begynnelse", "beginning", "en", "Det var en god begynnelse.", "It was a good beginning."),
    ("midt", "middle", "en", "Bordet står midt i rommet.", "The table is in the middle of the room."),
    ("side", "side/page", "ei", "Les side ti.", "Read page ten."),
    ("rekkefølge", "order/sequence", "en", "Sett dem i riktig rekkefølge.", "Put them in the correct order."),
    ("forskjell", "difference", "en", "Det er en stor forskjell.", "There is a big difference."),
    ("mening", "meaning/opinion", "ei", "Hva er meningen din?", "What is your opinion?"),
    ("regel", "rule", "en", "Følg reglene.", "Follow the rules."),
    ("vane", "habit", "en", "Det er en dårlig vane.", "It is a bad habit."),
    ("mål", "goal", "et", "Hva er målet ditt?", "What is your goal?"),
    ("resultat", "result", "et", "Resultatet var bra.", "The result was good."),
    ("årsak", "cause", "en", "Hva var årsaken til brannen?", "What was the cause of the fire?"),
    ("eksempel", "example", "et", "Gi meg et eksempel.", "Give me an example."),
    ("valg", "choice", "et", "Det er ditt valg.", "It is your choice."),
    ("mulighet", "opportunity", "en", "Dette er en god mulighet.", "This is a good opportunity."),
    ("framtid", "future", "ei", "Tenk på framtida.", "Think about the future."),
    ("fortid", "past", "ei", "Det tilhører fortida.", "It belongs to the past."),
    ("nåtid", "present", "ei", "Lev i nåtida.", "Live in the present."),
]

VERBS_C = [
    ("tegne", "draw", "Barnet tegner et hus.", "The child draws a house."),
    ("male", "paint", "Vi maler veggen blå.", "We paint the wall blue."),
    ("klippe", "cut (with scissors)", "Jeg klipper håret mitt.", "I cut my hair."),
    ("brette", "fold", "Hun bretter klærne.", "She folds the clothes."),
    ("henge", "hang", "Heng jakka på kroken.", "Hang the jacket on the hook."),
    ("plukke", "pick", "Vi plukker bær i skogen.", "We pick berries in the forest."),
    ("plante", "plant", "Vi planter blomster i hagen.", "We plant flowers in the garden."),
    ("grave", "dig", "Hunden graver et hull.", "The dog digs a hole."),
    ("bære", "carry", "Kan du bære veska?", "Can you carry the bag?"),
    ("dra", "pull/go", "Vi drar til byen i morgen.", "We are going to the city tomorrow."),
    ("dytte", "push", "Ikke dytt!", "Don't push!"),
    ("løfte", "lift", "Han løfter den tunge esken.", "He lifts the heavy box."),
    ("slippe", "drop/let go", "Ikke slipp glasset!", "Don't drop the glass!"),
    ("holde", "hold", "Hold hånda mi.", "Hold my hand."),
    ("trykke", "press", "Trykk på knappen.", "Press the button."),
    ("riste", "shake", "Rist flaska før bruk.", "Shake the bottle before use."),
    ("blande", "mix", "Bland sukker og mel.", "Mix sugar and flour."),
    ("helle", "pour", "Hell melk i glasset.", "Pour milk into the glass."),
    ("kutte", "cut", "Kutt grønnsakene i biter.", "Cut the vegetables into pieces."),
    ("smøre", "spread/butter", "Smør smør på brødet.", "Spread butter on the bread."),
    ("servere", "serve", "De serverer frokost klokka sju.", "They serve breakfast at seven o'clock."),
    ("rope", "shout", "Han ropte navnet mitt.", "He shouted my name."),
    ("hviske", "whisper", "Hun hvisket i øret mitt.", "She whispered in my ear."),
    ("synge med", "sing along", "Alle sang med på sangen.", "Everyone sang along to the song."),
    ("le av", "laugh at", "Ikke le av meg.", "Don't laugh at me."),
    ("gjette", "guess", "Kan du gjette hvor gammel jeg er?", "Can you guess how old I am?"),
    ("oppdage", "discover", "De oppdaget en feil.", "They discovered a mistake."),
    ("merke", "notice", "Jeg merket ikke at du kom.", "I didn't notice that you came."),
    ("kjenne igjen", "recognize", "Jeg kjente deg ikke igjen.", "I didn't recognize you."),
    ("lære seg", "learn (a skill)", "Han lærte seg å svømme.", "He learned to swim."),
    ("undre seg", "wonder", "Jeg undrer meg på hvorfor.", "I wonder why."),
    ("bestå", "pass (a test)", "Hun besto eksamen.", "She passed the exam."),
    ("stryke", "fail (a test)", "Han strøk på prøven.", "He failed the test."),
    ("samle", "collect", "Gutten samler på frimerker.", "The boy collects stamps."),
    ("pakke", "pack", "Jeg pakker kofferten.", "I am packing the suitcase."),
    ("ankomme", "arrive", "Toget ankommer klokka ti.", "The train arrives at ten o'clock."),
    ("forlate", "leave", "Vi forlater huset klokka åtte.", "We leave the house at eight o'clock."),
    ("returnere", "return", "Jeg må returnere boka.", "I have to return the book."),
    ("bytte", "swap/change", "Kan vi bytte plass?", "Can we swap seats?"),
    ("koste på seg", "treat oneself", "I dag koster jeg på meg en kake.", "Today I treat myself to a cake."),
    ("spørre om", "ask for", "Jeg spør om veien.", "I ask for directions."),
    ("svare på", "reply to", "Jeg må svare på e-posten.", "I have to reply to the email."),
    ("ringe til", "phone", "Jeg ringer til legen.", "I am phoning the doctor."),
    ("sende inn", "submit", "Jeg sendte inn søknaden.", "I submitted the application."),
    ("fylle ut", "fill in", "Fyll ut skjemaet.", "Fill in the form."),
    ("skrive ned", "write down", "Skriv ned adressen.", "Write down the address."),
    ("slå opp", "look up", "Slå opp ordet i ordboka.", "Look up the word in the dictionary."),
]

ADJECTIVES_C = [
    ("billig", "inexpensive", "Denne butikken er billig.", "This shop is inexpensive."),
    ("dyrebar", "precious", "Tiden er dyrebar.", "Time is precious."),
    ("nyttig", "useful", "Dette verktøyet er nyttig.", "This tool is useful."),
    ("ubrukelig", "useless", "Den gamle telefonen er ubrukelig.", "The old phone is useless."),
    ("vått", "damp", "Gresset er vått om morgenen.", "The grass is damp in the morning."),
    ("kjølig", "cool", "Det er kjølig i kjelleren.", "It is cool in the basement."),
    ("varmende", "warming", "Suppa er varmende.", "The soup is warming."),
    ("frisk", "fresh (air)", "Vi trenger frisk luft.", "We need fresh air."),
    ("travel", "hectic", "Det var en travel dag.", "It was a hectic day."),
    ("stille", "quiet", "Det er stille om natta.", "It is quiet at night."),
    ("høylytt", "loud", "Musikken er for høylytt.", "The music is too loud."),
    ("vidunderlig", "wonderful", "For en vidunderlig dag!", "What a wonderful day!"),
    ("forferdelig", "terrible", "Været er forferdelig.", "The weather is terrible."),
    ("perfekt", "perfect", "Dette er en perfekt dag.", "This is a perfect day."),
    ("normal", "normal", "Alt er helt normalt.", "Everything is completely normal."),
    ("merkelig", "odd", "Det var en merkelig lyd.", "That was an odd sound."),
    ("vakker", "gorgeous", "Utsikten er vakker.", "The view is gorgeous."),
    ("stusselig", "dreary", "Rommet var litt stusselig.", "The room was a bit dreary."),
    ("behagelig", "comfortable", "Stolen er behagelig.", "The chair is comfortable."),
    ("ubehagelig", "uncomfortable", "Det var en ubehagelig følelse.", "It was an uncomfortable feeling."),
    ("sliten", "worn out/tired", "Jeg er helt sliten i dag.", "I am completely worn out today."),
    ("frisk", "well/recovered", "Jeg er frisk igjen.", "I am well again."),
    ("voksen", "grown-up", "Han oppfører seg voksent.", "He behaves in a grown-up way."),
    ("ledig", "free (time)", "Er du ledig på fredag?", "Are you free on Friday?"),
    ("opptatt", "occupied", "Toalettet er opptatt.", "The toilet is occupied."),
]

PHRASES_C = [
    ("Ha det!", "Bye!"),
    ("Snakkes!", "Talk soon!"),
    ("Hva skjer?", "What's up?"),
    ("Det går fint.", "It's going fine."),
    ("Jeg har det bra.", "I am doing well."),
    ("Hyggelig å se deg.", "Nice to see you."),
    ("Kan du si det igjen?", "Can you say that again?"),
    ("Hva mener du?", "What do you mean?"),
    ("Jeg er enig med deg.", "I agree with you."),
    ("Jeg er uenig.", "I disagree."),
    ("Det spiller ingen rolle.", "It doesn't matter."),
    ("Det er opp til deg.", "It's up to you."),
    ("Jeg trenger litt hjelp.", "I need a little help."),
    ("Vær så snill og vent.", "Please wait."),
    ("Kan jeg få regningen, takk?", "Can I have the bill, please?"),
    ("Hvor skal vi møtes?", "Where shall we meet?"),
    ("Jeg gleder meg!", "I'm looking forward to it!"),
    ("Ses vi senere?", "Will we see each other later?"),
    ("Pass på deg selv.", "Take care."),
    ("Det var hyggelig å prate.", "It was nice to chat."),
]

NOUNS_D = [
    ("luft", "air", "ei", "Lufta er frisk i fjellet.", "The air is fresh in the mountains."),
    ("ild", "fire", "en", "Ilden brenner i peisen.", "The fire burns in the fireplace."),
    ("jord", "earth/soil", "ei", "Jorda er våt etter regnet.", "The soil is wet after the rain."),
    ("verden", "Earth/world", "en", "Vi må ta vare på verden.", "We must take care of the world."),
    ("dyrehage", "zoo", "en", "Vi tok barna med til dyrehagen.", "We took the children to the zoo."),
    ("svømmebasseng", "swimming pool", "et", "Svømmebassenget er stort.", "The swimming pool is big."),
    ("treningssenter", "gym", "et", "Jeg går på treningssenteret.", "I go to the gym."),
    ("lekeplass", "playground", "en", "Barna leker på lekeplassen.", "The children play on the playground."),
    ("marked", "market", "et", "Vi kjøper grønnsaker på markedet.", "We buy vegetables at the market."),
    ("kjøpesenter", "shopping mall", "et", "Kjøpesenteret er fullt av folk.", "The mall is full of people."),
    ("restaurant", "restaurant", "en", "Vi spiser på en god restaurant.", "We eat at a good restaurant."),
    ("frimerke", "stamp", "et", "Jeg trenger et frimerke til brevet.", "I need a stamp for the letter."),
    ("pakke", "package", "en", "Pakka kom i posten i dag.", "The package came in the mail today."),
    ("post", "mail", "en", "Har det kommet noe post?", "Has any mail arrived?"),
    ("kvittering", "receipt", "ei", "Kan jeg få kvitteringa?", "Can I have the receipt?"),
    ("rabatt", "discount", "en", "Vi fikk ti prosent rabatt.", "We got a ten percent discount."),
    ("kontanter", "cash", "en", "Jeg har ikke kontanter på meg.", "I don't have cash on me."),
    ("kort", "card", "et", "Jeg betaler med kort.", "I pay by card."),
    ("konto", "account", "en", "Pengene står på kontoen.", "The money is in the account."),
    ("skatt", "tax", "en", "Vi betaler skatt hvert år.", "We pay tax every year."),
    ("lønn", "salary", "ei", "Lønna kommer den femtende.", "The salary comes on the fifteenth."),
    ("ledelse", "management", "en", "Ledelsen tok en avgjørelse.", "The management made a decision."),
    ("møte", "meeting", "et", "Møtet begynner klokka ni.", "The meeting begins at nine o'clock."),
    ("avtale", "appointment/agreement", "en", "Jeg har en avtale hos legen.", "I have an appointment at the doctor's."),
    ("ferie", "leave/time off", "en", "Jeg tar ferie i juli.", "I am taking time off in July."),
]

def build():
    cards = []
    for no, en, g, ex_no, ex_en in NOUNS + NOUNS_B + NOUNS_C + NOUNS_D:
        cards.append(card(no, en, "noun", ex_no, ex_en, gender=g))
    for root, en, ex_no, ex_en in VERBS + VERBS_B + VERBS_C:
        cards.append(card(f"å {root}", f"to {en}", "verb", ex_no, ex_en))
    for no, en, ex_no, ex_en in ADJECTIVES + ADJECTIVES_B + ADJECTIVES_C:
        cards.append(card(no, en, "adjective", ex_no, ex_en))
    for no, en, pos, ex_no, ex_en in OTHER + OTHER_B:
        cards.append(card(no, en, pos, ex_no, ex_en))
    for no, en in PHRASES + PHRASES_B + PHRASES_C:
        cards.append(card(no, en, "phrase", no, en, level="intermediate"))

    # de-duplicate by id, keeping first occurrence
    seen = {}
    for c in cards:
        seen.setdefault(c["id"], c)
    return list(seen.values())


if __name__ == "__main__":
    cards = build()
    out_path = os.path.join(os.path.dirname(__file__), "..", "public", "flashcards.json")
    out_path = os.path.abspath(out_path)
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(cards, f, ensure_ascii=False, indent=2)
    print(f"Wrote {len(cards)} cards to {out_path}")
